# Generated by Django 5.2 on 2025-04-08 00:13

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('cgm', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('guardian', models.CharField(max_length=100)),
                ('guardian_cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='Invalid CPF. Must contain exactly 11 digits.')])),
                ('address', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', message='Invalid postal code. Must contain exactly 8 digits.')])),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
    ]
