# Generated by Django 5.2 on 2025-04-10 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_cpf',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='Invalid CPF. Must contain exactly 11 digits.')]),
        ),
    ]
